version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: mytrader_postgres
    environment:
      POSTGRES_DB: mytrader
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mytrader"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mytrader_network

  mytrader_api:
    build: .
    container_name: mytrader_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=mytrader;Username=postgres;Password=password
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mytrader_network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  mytrader_network:
    driver: bridge